### ISSUE TITLE
you should call AGConnectApp.initialize first

### ISSUE THREAD

**Issue by AhmedAbogameel** [Tsagaanbayr1/agconnect_core#1]
```
E/MethodChannel#com.huawei.flutter/agconnect_core(17053): Failed to handle method call
E/MethodChannel#com.huawei.flutter/agconnect_core(17053): java.lang.IllegalStateException: you should call AGConnectApp.initialize first
E/MethodChannel#com.huawei.flutter/agconnect_core(17053): 	at com.huawei.agconnect.config.impl.a.a(Unknown Source:19)
E/MethodChannel#com.huawei.flutter/agconnect_core(17053): 	at com.huawei.agconnect.config.impl.a.a(Unknown Source:2)
E/MethodChannel#com.huawei.flutter/agconnect_core(17053): 	at com.huawei.agconnect.AGConnectApp.getInstance(Unknown Source:0)
E/MethodChannel#com.huawei.flutter/agconnect_core(17053): 	at com.huawei.agconnectcore.AGConnectCorePlugin.onMethodCall(AGConnectCorePlugin.java:69)
E/MethodChannel#com.huawei.flutter/agconnect_core(17053): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#com.huawei.flutter/agconnect_core(17053): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#com.huawei.flutter/agconnect_core(17053): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#com.huawei.flutter/agconnect_core(17053): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#com.huawei.flutter/agconnect_core(17053): 	at android.os.Handler.handleCallback(Handler.java:942)
E/MethodChannel#com.huawei.flutter/agconnect_core(17053): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#com.huawei.flutter/agconnect_core(17053): 	at android.os.Looper.loopOnce(Looper.java:201)
E/MethodChannel#com.huawei.flutter/agconnect_core(17053): 	at android.os.Looper.loop(Looper.java:288)
E/MethodChannel#com.huawei.flutter/agconnect_core(17053): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/MethodChannel#com.huawei.flutter/agconnect_core(17053): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#com.huawei.flutter/agconnect_core(17053): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/MethodChannel#com.huawei.flutter/agconnect_core(17053): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/MethodChannel#com.huawei.flutter/agconnect_core(17053): Failed to handle method call
E/MethodChannel#com.huawei.flutter/agconnect_core(17053): java.lang.IllegalStateException: you should call AGConnectApp.initialize first
E/MethodChannel#com.huawei.flutter/agconnect_core(17053): 	at com.huawei.agconnect.config.impl.a.a(Unknown Source:19)
E/MethodChannel#com.huawei.flutter/agconnect_core(17053): 	at com.huawei.agconnect.config.impl.a.a(Unknown Source:2)
E/MethodChannel#com.huawei.flutter/agconnect_core(17053): 	at com.huawei.agconnect.AGConnectApp.getInstance(Unknown Source:0)
E/MethodChannel#com.huawei.flutter/agconnect_core(17053): 	at com.huawei.agconnectcore.AGConnectCorePlugin.onMethodCall(AGConnectCorePlugin.java:75)
E/MethodChannel#com.huawei.flutter/agconnect_core(17053): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#com.huawei.flutter/agconnect_core(17053): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#com.huawei.flutter/agconnect_core(17053): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#com.huawei.flutter/agconnect_core(17053): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#com.huawei.flutter/agconnect_core(17053): 	at android.os.Handler.handleCallback(Handler.java:942)
E/MethodChannel#com.huawei.flutter/agconnect_core(17053): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#com.huawei.flutter/agconnect_core(17053): 	at android.os.Looper.loopOnce(Looper.java:201)
E/MethodChannel#com.huawei.flutter/agconnect_core(17053): 	at android.os.Looper.loop(Looper.java:288)
E/MethodChannel#com.huawei.flutter/agconnect_core(17053): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/MethodChannel#com.huawei.flutter/agconnect_core(17053): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#com.huawei.flutter/agconnect_core(17053): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/MethodChannel#com.huawei.flutter/agconnect_core(17053): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/MethodChannel#com.huawei.flutter/agconnect_core(17053): Failed to handle method call
E/MethodChannel#com.huawei.flutter/agconnect_core(17053): java.lang.IllegalStateException: you should call AGConnectApp.initialize first
E/MethodChannel#com.huawei.flutter/agconnect_core(17053): 	at com.huawei.agconnect.config.impl.a.a(Unknown Source:19)
E/MethodChannel#com.huawei.flutter/agconnect_core(17053): 	at com.huawei.agconnect.config.impl.a.a(Unknown Source:2)
E/MethodChannel#com.huawei.flutter/agconnect_core(17053): 	at com.huawei.agconnect.AGConnectApp.getInstance(Unknown Source:0)
E/MethodChannel#com.huawei.flutter/agconnect_core(17053): 	at com.huawei.agconnectcore.AGConnectCorePlugin.onMethodCall(AGConnectCorePlugin.java:63)
E/MethodChannel#com.huawei.flutter/agconnect_core(17053): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#com.huawei.flutter/agconnect_core(17053): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#com.huawei.flutter/agconnect_core(17053): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#com.huawei.flutter/agconnect_core(17053): 	at io.flutter.embedding.engine.dart
```

where to get AGConnectApp.initialize ?

**Comment by Tsagaanbayr1** [comment]
Hey Ahmed,
I'm glad you've tried our package. It's currently out of date since we created it. I will update it with the tested code as soon as possible. You can track the progress here: [Issue #2 ](https://github.com/Tsagaanbayr1/agconnect_core/issues/2)
